import { Movie, NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'NOVIDADES', href: '/category/novidades' },
  { label: 'FAROESTE', href: '/category/faroeste' },
  { label: 'GUERRA', href: '/category/guerra' },
  { label: 'NOIR/POLICIAL', href: '/category/noir-policial-crime' },
  { label: 'CLÁSSICO/ÉPICO', href: '/category/classico-epico' },
  { label: 'AVENTURA', href: '/category/aventura' },
  { label: 'OUTROS', href: '/category/outros' },
];

// Catálogo expandido baseado no Prompt Cine Classic
export const MOVIES: Movie[] = [
  // --- FAROESTE AMERICANO (JOHN WAYNE & CLÁSSICOS) ---
  {
    id: 1,
    title: "RASTROS DE ÓDIO",
    originalTitle: "The Searchers",
    year: "1956",
    director: "John Ford",
    cast: ["John Wayne", "Jeffrey Hunter", "Vera Miles", "Natalie Wood"],
    category: "Faroeste",
    price: 29.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/jPeM7mK4j02p9F7ZPTgYm0t8I5H.jpg", // Poster realístico ou placeholder
    tags: ["Colorido", "Obra-prima", "John Ford"],
    specs: { type: 'Colorido', duration: '119 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "Ethan Edwards, um veterano da Guerra Civil, embarca em uma jornada de anos para resgatar sua sobrinha sequestrada pelos Comanches. Uma história profunda sobre obsessão, racismo e redenção no oeste selvagem.",
    curiosities: "John Wayne considerava este seu melhor papel. A cena final da porta se fechando é uma das mais icônicas da história do cinema.",
    importance: "Frequentemente citado como o maior Western já feito, influenciou diretores como Steven Spielberg e Martin Scorsese."
  },
  {
    id: 2,
    title: "RIO BRAVO",
    originalTitle: "Rio Bravo",
    year: "1959",
    director: "Howard Hawks",
    cast: ["John Wayne", "Dean Martin", "Ricky Nelson", "Angie Dickinson"],
    category: "Faroeste",
    price: 24.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/z6c9zZgC9zH9zZ1z9z9z9z9z9.jpg", // Placeholder URL structure
    tags: ["Colorido", "Ação", "Howard Hawks"],
    specs: { type: 'Colorido', duration: '141 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "Um xerife de uma pequena cidade no oeste americano deve impedir que um poderoso rancheiro resgate seu irmão da prisão, contando apenas com a ajuda de um bêbado, um velho e um jovem pistoleiro.",
    curiosities: "Feito como uma resposta conservadora ao filme 'Matar ou Morrer' (High Noon), que Hawks e Wayne detestavam.",
    importance: "Redefiniu o arquétipo do grupo de heróis improváveis defendendo um local sitiado."
  },
  {
    id: 3,
    title: "NO TEMPO DAS DILIGÊNCIAS",
    originalTitle: "Stagecoach",
    year: "1939",
    director: "John Ford",
    cast: ["John Wayne", "Claire Trevor", "Thomas Mitchell"],
    category: "Faroeste",
    price: 19.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/5jX9q7.jpg",
    tags: ["Preto e Branco", "Clássico", "John Wayne"],
    specs: { type: 'Preto e Branco', duration: '96 min', country: 'EUA', studio: 'United Artists' },
    description: "Um grupo heterogêneo de estranhos viaja em uma diligência através do perigoso território Apache. Entre eles está Ringo Kid, um fora da lei em busca de vingança.",
    curiosities: "Foi o filme que transformou John Wayne, até então ator de filmes B, em uma estrela de primeira grandeza.",
    importance: "Elevou o gênero Western de 'filme de matinê' para cinema de arte respeitável."
  },
  {
    id: 4,
    title: "O HOMEM QUE MATOU O FACÍNORA",
    originalTitle: "The Man Who Shot Liberty Valance",
    year: "1962",
    director: "John Ford",
    cast: ["John Wayne", "James Stewart", "Lee Marvin", "Vera Miles"],
    category: "Faroeste",
    price: 25.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleLiberty.jpg",
    tags: ["Preto e Branco", "Drama", "Política"],
    specs: { type: 'Preto e Branco', duration: '123 min', country: 'EUA', studio: 'Paramount' },
    description: "Um senador retorna a uma pequena cidade do oeste para o funeral de um velho amigo e conta a verdade sobre a lenda de como ele matou o notório bandido Liberty Valance.",
    curiosities: "Filmado em preto e branco numa época em que o colorido já era padrão, para aumentar a atmosfera nostálgica e sombria.",
    importance: "Uma desconstrução melancólica do mito do Oeste, explorando a transição da lei das armas para a lei dos livros."
  },

  // --- BANG BANG ITALIANO (SPAGHETTI WESTERN) ---
  {
    id: 5,
    title: "TRÊS HOMENS EM CONFLITO",
    originalTitle: "Il buono, il brutto, il cattivo",
    year: "1966",
    director: "Sergio Leone",
    cast: ["Clint Eastwood", "Lee Van Cleef", "Eli Wallach"],
    category: "Faroeste",
    price: 29.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleGoodBad.jpg",
    tags: ["Colorido", "Spaghetti Western", "Clint Eastwood"],
    specs: { type: 'Colorido', duration: '178 min', country: 'Itália/Espanha', studio: 'PEA' },
    description: "Durante a Guerra Civil Americana, três pistoleiros rivais - o Bom, o Mau e o Feio - formam alianças instáveis em uma busca implacável por um tesouro de ouro confederado.",
    curiosities: "A ponte explodida no filme teve que ser reconstruída e explodida uma segunda vez porque as câmeras não estavam rodando na primeira tentativa.",
    importance: "A quintessência do Spaghetti Western, com a trilha sonora imortal de Ennio Morricone."
  },
  {
    id: 6,
    title: "ERA UMA VEZ NO OESTE",
    originalTitle: "C'era una volta il West",
    year: "1968",
    director: "Sergio Leone",
    cast: ["Henry Fonda", "Charles Bronson", "Claudia Cardinale", "Jason Robards"],
    category: "Faroeste",
    price: 29.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleWest.jpg",
    tags: ["Colorido", "Épico", "Ennio Morricone"],
    specs: { type: 'Colorido', duration: '165 min', country: 'Itália/EUA', studio: 'Paramount' },
    description: "Uma misteriosa harmônica toca enquanto um estranho busca vingança contra um assassino implacável em uma batalha violenta pela posse de terras ferroviárias.",
    curiosities: "Henry Fonda, conhecido por papéis de heróis, chocou o público ao interpretar um vilão sádico que mata crianças.",
    importance: "Considerado por muitos críticos como o filme mais operístico e visualmente impressionante de Sergio Leone."
  },
  {
    id: 7,
    title: "DJANGO",
    originalTitle: "Django",
    year: "1966",
    director: "Sergio Corbucci",
    cast: ["Franco Nero", "José Bódalo", "Loredana Nusciak"],
    category: "Faroeste",
    price: 22.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleDjango.jpg",
    tags: ["Colorido", "Cult", "Violento"],
    specs: { type: 'Colorido', duration: '92 min', country: 'Itália/Espanha', studio: 'B.R.C.' },
    description: "Um pistoleiro solitário arrastando um caixão chega a uma cidade enlameada apanhada em uma disputa violenta entre a KKK e bandidos mexicanos.",
    curiosities: "O filme foi banido no Reino Unido por anos devido à sua violência extrema (para a época), incluindo a cena da orelha cortada.",
    importance: "Criou um dos anti-heróis mais imitados do cinema e gerou dezenas de sequências não oficiais."
  },

  // --- GUERRA ---
  {
    id: 8,
    title: "OS DOZE CONDENADOS",
    originalTitle: "The Dirty Dozen",
    year: "1967",
    director: "Robert Aldrich",
    cast: ["Lee Marvin", "Ernest Borgnine", "Charles Bronson", "Jim Brown"],
    category: "Guerra",
    price: 24.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleDirty.jpg",
    tags: ["Colorido", "Ação", "Segunda Guerra"],
    specs: { type: 'Colorido', duration: '150 min', country: 'EUA', studio: 'MGM' },
    description: "Um major rebelde treina doze prisioneiros condenados à morte ou prisão perpétua para uma missão suicida atrás das linhas inimigas nazistas antes do Dia D.",
    curiosities: "O filme foi criticado na época por sua violência e tom anárquico, mas tornou-se um enorme sucesso de bilheteria.",
    importance: "Estabeleceu o subgênero de filmes de 'homens em missão' (men on a mission)."
  },
  {
    id: 9,
    title: "APOCALYPSE NOW",
    originalTitle: "Apocalypse Now",
    year: "1979",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Martin Sheen", "Robert Duvall"],
    category: "Guerra",
    price: 35.00,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleApoc.jpg",
    tags: ["Colorido", "Psicológico", "Vietnã"],
    specs: { type: 'Colorido', duration: '147 min', country: 'EUA', studio: 'Zoetrope' },
    description: "Durante a Guerra do Vietnã, o Capitão Willard é enviado ao Camboja em uma missão secreta para assassinar um Coronel renegado que enlouqueceu.",
    curiosities: "A produção foi um pesadelo lendário: cenários destruídos por tufões, Martin Sheen teve um ataque cardíaco e Brando chegou acima do peso.",
    importance: "Uma visão alucinante e filosófica sobre a loucura da guerra, baseada em 'O Coração das Trevas' de Conrad."
  },
  {
    id: 10,
    title: "A PONTE DO RIO KWAI",
    originalTitle: "The Bridge on the River Kwai",
    year: "1957",
    director: "David Lean",
    cast: ["William Holden", "Alec Guinness", "Jack Hawkins"],
    category: "Guerra",
    price: 22.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleKwai.jpg",
    tags: ["Colorido", "Oscar", "Segunda Guerra"],
    specs: { type: 'Colorido', duration: '161 min', country: 'Reino Unido/EUA', studio: 'Columbia' },
    description: "Prisioneiros de guerra britânicos são forçados a construir uma ponte ferroviária para seus captores japoneses, enquanto seu comandante fica obcecado em fazer um trabalho perfeito.",
    curiosities: "Os roteiristas reais estavam na lista negra de Hollywood e não receberam crédito nem o Oscar na época.",
    importance: "Vencedor de 7 Oscars, é um estudo complexo sobre honra, loucura e futilidade militar."
  },

  // --- NOIR / POLICIAL ---
  {
    id: 11,
    title: "RELÍQUIA MACABRA",
    originalTitle: "The Maltese Falcon",
    year: "1941",
    director: "John Huston",
    cast: ["Humphrey Bogart", "Mary Astor", "Peter Lorre"],
    category: "Noir/Policial/Crime",
    price: 21.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleMaltese.jpg",
    tags: ["Preto e Branco", "Humphrey Bogart", "Detetive"],
    specs: { type: 'Preto e Branco', duration: '100 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "O detetive particular Sam Spade se envolve em uma caça perigosa por uma estatueta inestimável, lidando com uma galeria de criminosos excêntricos e uma mulher fatal.",
    curiosities: "Considerado frequentemente o primeiro grande filme Noir. A estatueta original foi vendida em leilão por mais de 4 milhões de dólares.",
    importance: "Definiu o arquétipo do detetive 'hard-boiled' e lançou a carreira de diretor de John Huston."
  },
  {
    id: 12,
    title: "PACTO DE SANGUE",
    originalTitle: "Double Indemnity",
    year: "1944",
    director: "Billy Wilder",
    cast: ["Fred MacMurray", "Barbara Stanwyck", "Edward G. Robinson"],
    category: "Noir/Policial/Crime",
    price: 21.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleDouble.jpg",
    tags: ["Preto e Branco", "Femme Fatale", "Suspense"],
    specs: { type: 'Preto e Branco', duration: '107 min', country: 'EUA', studio: 'Paramount' },
    description: "Um vendedor de seguros se deixa seduzir por uma esposa manipuladora e planeja o assassinato do marido dela para receber o dinheiro de uma apólice de seguro.",
    curiosities: "O final original, onde o protagonista morria na câmara de gás, foi filmado mas cortado por ser considerado muito sombrio.",
    importance: "O padrão-ouro do Film Noir, com diálogos afiados e a definitiva femme fatale."
  },
  {
    id: 13,
    title: "PERDIGUEIRO",
    originalTitle: "Dirty Harry",
    year: "1971",
    director: "Don Siegel",
    cast: ["Clint Eastwood", "Harry Guardino", "Reni Santoni"],
    category: "Noir/Policial/Crime",
    price: 24.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleHarry.jpg",
    tags: ["Colorido", "Policial", "Anos 70"],
    specs: { type: 'Colorido', duration: '102 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "Harry Callahan, um inspetor de polícia de São Francisco que não segue regras, persegue o assassino em série 'Scorpio' que aterroriza a cidade.",
    curiosities: "A famosa arma de Harry, a .44 Magnum, tornou-se um ícone cultural após o filme.",
    importance: "Mudou a cara dos filmes policiais, introduzindo o policial anti-herói que faz justiça com as próprias mãos."
  },

  // --- CLÁSSICO / ÉPICO ---
  {
    id: 14,
    title: "BEN-HUR",
    originalTitle: "Ben-Hur",
    year: "1959",
    director: "William Wyler",
    cast: ["Charlton Heston", "Jack Hawkins", "Stephen Boyd"],
    category: "Classico-Epico",
    price: 29.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleBenHur.jpg",
    tags: ["Colorido", "Bíblico", "Oscar"],
    specs: { type: 'Colorido', duration: '212 min', country: 'EUA', studio: 'MGM' },
    description: "Um príncipe judeu é traído e enviado para a escravidão por um amigo romano, mas recupera sua liberdade e volta para se vingar na arena de corrida de bigas.",
    curiosities: "A corrida de bigas não teve efeitos especiais de computador e levou 5 semanas para ser filmada com 15.000 figurantes.",
    importance: "Vencedor de 11 Oscars, um recorde que durou décadas. É o ápice do épico de Hollywood."
  },
  {
    id: 15,
    title: "SPARTACUS",
    originalTitle: "Spartacus",
    year: "1960",
    director: "Stanley Kubrick",
    cast: ["Kirk Douglas", "Laurence Olivier", "Jean Simmons", "Tony Curtis"],
    category: "Classico-Epico",
    price: 26.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleSpartacus.jpg",
    tags: ["Colorido", "Histórico", "Roma"],
    specs: { type: 'Colorido', duration: '197 min', country: 'EUA', studio: 'Universal' },
    description: "A história do escravo Spartacus, que lidera uma revolta violenta contra a decadente República Romana.",
    curiosities: "Kirk Douglas contratou o roteirista Dalton Trumbo, que estava na Lista Negra, quebrando efetivamente o boicote anticomunista em Hollywood.",
    importance: "Um épico intelectual que combina espetáculo visual com temas políticos profundos."
  },
  
  // --- AVENTURA & OUTROS ---
  {
    id: 16,
    title: "O TESOURO DE SIERRA MADRE",
    originalTitle: "The Treasure of the Sierra Madre",
    year: "1948",
    director: "John Huston",
    cast: ["Humphrey Bogart", "Walter Huston", "Tim Holt"],
    category: "Aventura",
    price: 21.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleSierra.jpg",
    tags: ["Preto e Branco", "Aventura", "Psicológico"],
    specs: { type: 'Preto e Branco', duration: '126 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "Três americanos sem sorte no México partem em busca de ouro nas montanhas de Sierra Madre, mas a ganância e a paranoia ameaçam destruí-los.",
    curiosities: "Walter Huston, pai do diretor John Huston, ganhou o Oscar de Melhor Ator Coadjuvante (e John ganhou Melhor Diretor).",
    importance: "Um dos maiores estudos sobre a ganância humana já filmados."
  },
  {
    id: 17,
    title: "CASABLANCA",
    originalTitle: "Casablanca",
    year: "1942",
    director: "Michael Curtiz",
    cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"],
    category: "Outros",
    price: 25.00,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleCasablanca.jpg",
    tags: ["Preto e Branco", "Romance", "Guerra"],
    specs: { type: 'Preto e Branco', duration: '102 min', country: 'EUA', studio: 'Warner Bros.' },
    description: "Em Casablanca, no Marrocos, durante a Segunda Guerra Mundial, um exilado americano cínico encontra uma antiga amante e deve decidir entre o amor e a luta contra os nazistas.",
    curiosities: "Ninguém sabia como o filme terminaria até os últimos dias de filmagem.",
    importance: "Frequentemente citado como um dos roteiros mais perfeitos da história do cinema."
  },
  {
    id: 18,
    title: "PSICOSE",
    originalTitle: "Psycho",
    year: "1960",
    director: "Alfred Hitchcock",
    cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles"],
    category: "Outros",
    price: 22.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SamplePsycho.jpg",
    tags: ["Preto e Branco", "Terror", "Hitchcock"],
    specs: { type: 'Preto e Branco', duration: '109 min', country: 'EUA', studio: 'Paramount' },
    description: "Uma secretária em fuga rouba dinheiro de seu empregador e se hospeda em um motel isolado administrado por um jovem estranho e sua mãe dominadora.",
    curiosities: "Hitchcock comprou todas as cópias do livro original para que ninguém soubesse o final do filme.",
    importance: "Inventou o gênero 'slasher' moderno e mudou a forma como a violência e a sexualidade eram mostradas no cinema."
  },
  {
    id: 19,
    title: "2001: UMA ODISSEIA NO ESPAÇO",
    originalTitle: "2001: A Space Odyssey",
    year: "1968",
    director: "Stanley Kubrick",
    cast: ["Keir Dullea", "Gary Lockwood"],
    category: "Outros",
    price: 29.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/Sample2001.jpg",
    tags: ["Colorido", "Sci-Fi", "Filosófico"],
    specs: { type: 'Colorido', duration: '149 min', country: 'Reino Unido/EUA', studio: 'MGM' },
    description: "Após a descoberta de um misterioso artefato alienígena enterrado na Lua, uma nave espacial é enviada a Júpiter para encontrar suas origens, controlada pelo computador senciente HAL 9000.",
    curiosities: "Não há diálogo nos primeiros 25 minutos nem nos últimos 23 minutos do filme.",
    importance: "O filme de ficção científica mais influente já feito, conhecido por seus efeitos especiais pioneiros e precisão científica."
  },
  {
    id: 20,
    title: "CANTANDO NA CHUVA",
    originalTitle: "Singin' in the Rain",
    year: "1952",
    director: "Stanley Donen, Gene Kelly",
    cast: ["Gene Kelly", "Donald O'Connor", "Debbie Reynolds"],
    category: "Outros",
    price: 19.90,
    imageUrl: "https://image.tmdb.org/t/p/w500/SampleRain.jpg",
    tags: ["Colorido", "Musical", "Comédia"],
    specs: { type: 'Colorido', duration: '103 min', country: 'EUA', studio: 'MGM' },
    description: "Uma estrela do cinema mudo, seu parceiro e uma aspirante a atriz lidam com a difícil transição para o cinema falado na Hollywood dos anos 20.",
    curiosities: "Gene Kelly estava com 39 graus de febre quando filmou a famosa cena da dança na chuva.",
    importance: "Amplamente considerado o melhor musical de Hollywood de todos os tempos."
  }
];